# Generated by Django 4.2.6 on 2024-01-28 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('igdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PLAYING', 'Playing'), ('FINISHED', 'Finished'), ('ABANDONED', 'Abandoned')], default='NEW', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.collection')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igdb.game')),
                ('lists', models.ManyToManyField(blank=True, to='profiles.list')),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='igdb.platform')),
            ],
        ),
        migrations.CreateModel(
            name='Playthrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.collectiongame')),
            ],
        ),
    ]
